services:
  playit:
    build: .
    container_name: playit
    image: playit
    network_mode: host
    command: ["-s", "--secret", "<YOUR SECRET KEY>", "--platform_docker", "start"]
    restart: unless-stopped